name: FTP Connection Test

on:
  workflow_dispatch:   # 手动触发，用于测试

jobs:
  ftp-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test FTP Connection
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./        # 不上传文
          server-dir: ${{ secrets.FTP_PATH }}
          port: 21
          security: insecure
          dry-run: true        # 不实际上传，模拟测试
